var Mine = cc.Node.extend({
    ctor: function() {
        this._super();
        this.WIDTH = 40;
        this.HEIGHT = 30;
        this.MAP = [
            'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOO1OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO1OOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOO1OOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOO1OOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOO1OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOO1OOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOO1OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOO1OOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOO1OOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOO1OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO1OOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOO1OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOO1OOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX',
            'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        ];
 
        // ...  code for drawing the maze has be left out
 
    }
});